### ISSUE TITLE
Error starting app

### ISSUE THREAD

**Issue by HackIvan** [jaewonhimnae/react-shop-app#4]
When I do yarn start
gives error on that the app cannot start

**Comment by HackIvan** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/amor/.nvm/versions/node/v14.2.0/bin/node',
1 verbose cli   '/home/amor/.nvm/versions/node/v14.2.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-boiler-plate@1.0.0~prestart: react-boiler-plate@1.0.0
6 info lifecycle react-boiler-plate@1.0.0~start: react-boiler-plate@1.0.0
7 verbose lifecycle react-boiler-plate@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-boiler-plate@1.0.0~start: PATH: /home/amor/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/amor/react-shop-app/node_modules/.bin:/home/amor/.local/bin:/home/amor/.rbenv/plugins/ruby-build/bin:/home/amor/.rbenv/shims:/home/amor/.rbenv/bin:/home/amor/.nvm/versions/node/v14.2.0/bin:/home/amor/.deno/deno:/home/amor/.deno:/home/amor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/dart/bin:home/amor/.deno/deno:home/amor/.deno:flutter/bin:android/sdk:android/sdk/tools:android/sdk/tools/bin:android/sdk/platform-tools:/usr/lib/dart/bin
9 verbose lifecycle react-boiler-plate@1.0.0~start: CWD: /home/amor/react-shop-app
10 silly lifecycle react-boiler-plate@1.0.0~start: Args: [ '-c', 'node server/index.js' ]
11 silly lifecycle react-boiler-plate@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle react-boiler-plate@1.0.0~start: Failed to exec start script
13 verbose stack Error: react-boiler-plate@1.0.0 start: `node server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/amor/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/amor/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid react-boiler-plate@1.0.0
15 verbose cwd /home/amor/react-shop-app
16 verbose Linux 5.4.0-33-generic
17 verbose argv "/home/amor/.nvm/versions/node/v14.2.0/bin/node" "/home/amor/.nvm/versions/node/v14.2.0/bin/npm" "start"
18 verbose node v14.2.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error react-boiler-plate@1.0.0 start: `node server/index.js`
22 error Exit status 1
23 error Failed at the react-boiler-plate@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
